// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StudieJobsFinderMyDatabase.Models;

[Table("Studerende")]
public partial class Studerende
{
    [Key]
    [Column("StudentID")]
    public int StudentId { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Fornavn { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Efternavn { get; set; }

    [Column(TypeName = "date")]
    public DateTime? Fødselsdato { get; set; }

    [StringLength(1)]
    [Unicode(false)]
    public string Køn { get; set; }

    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    [StringLength(20)]
    [Unicode(false)]
    public string Telefonnummer { get; set; }

    [StringLength(255)]
    [Unicode(false)]
    public string Addresse { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ByNavn { get; set; }

    [StringLength(4)]
    [Unicode(false)]
    public string PostNummer { get; set; }

    [Column(TypeName = "text")]
    public string Kompetencer { get; set; }
}